{
 "title": "Inference Rate",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "TorchServe Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Inference Latency over 15min window (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "sum(delta(ts_inference_latency_microseconds[15m])) by(model_name,model_version) / sum(delta(ts_inference_requests_total[15m])) by(model_name,model_version) /1e4",
     "legendFormat": "{{model_name}}-{{model_version}}"
    }
   ]
  },
  {
   "title": "Rolling Inference Request Rate (per 10 Minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Request / 10 Min" }
   ],
   "targets": [
    {
     "expr": "sum(delta(ts_inference_requests_total[10m])) by(model_name,model_version)",
     "legendFormat": "{{model_name}}:{{model_version}}"
    }
   ]
  },
  { "title": "GPU Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average GPU Utilization (over 5min window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Percent Used (%)" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(DCGM_FI_DEV_GPU_UTIL[5m])",
     "legendFormat": "GPU-{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization (5min rolling avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Percent Used (%)" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(DCGM_FI_DEV_FB_USED[5m]) / (avg_over_time(DCGM_FI_DEV_FB_USED[5m])+avg_over_time(DCGM_FI_DEV_FB_FREE[5m]))*100"
    }
   ]
  },
  { "title": "Hardware Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE" }
   ]
  },
  {
   "title": "GPU Error Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(DCGM_FI_DEV_XID_ERRORS[1d])",
     "legendFormat": "Daily"
    },
    {
     "expr": "avg_over_time(DCGM_FI_DEV_XID_ERRORS[1h])",
     "legendFormat": "Hourly"
    }
   ]
  }
 ]
}