#!/bin/bash


source ./config.txt

#poetry run torch-model-archiver --model-name $MODEL_NAME --version $VERSION --model-file $MODEL_FILE --serialized-file $SERIALIZED_FILE --handler $HANDLER --extra-files $EXTRA_FILES
#curl -X POST  "http://localhost:8081/models?ur.mar"

